const EVENTO_ADD = "EVENTO_ADD";
const PROPUESTA_ADD = "PROPUESTA_ADD";
const POLITICO_ADD = "POLITICO_ADD";

const EVENTO_UPDATE = "EVENTO_UPDATE";
const PROPUESTA_UPDATE = "PROPUESTA_UPDATE";
const POLITICO_UPDATE = "POLITICO_UPDATE";

const EVENTO_DELETE = "EVENTO_DELETE";
const PROPUESTA_DELETE = "PROPUESTA_DELETE";
const POLITICO_DELETE = "POLITICO_DELETE";

const PATCH_EVENTO_ADD = "PATCH_EVENTO_ADD";
const PATCH_PROPUESTA_ADD = "PATCH_PROPUESTA_ADD";
const PATCH_POLITICO_ADD = "PATCH_POLITICO_ADD";

const PATCH_EVENTO_UPDATE = "PATCH_EVENTO_UPDATE";
const PATCH_PROPUESTA_UPDATE = "PATCH_PROPUESTA_UPDATE";
const PATCH_POLITICO_UPDATE = "PATCH_POLITICO_UPDATE";

const PATCH_EVENTO_DELETE = "PATCH_EVENTO_DELETE";
const PATCH_PROPUESTA_DELETE = "PATCH_PROPUESTA_DELETE";
const PATCH_POLITICO_DELETE = "PATCH_POLITICO_DELETE";

const PATCHD_EVENTO_ADD = "PATCHD_EVENTO_ADD";
const PATCHD_PROPUESTA_ADD = "PATCHD_PROPUESTA_ADD";
const PATCHD_POLITICO_ADD = "PATCHD_POLITICO_ADD";

const PATCHD_EVENTO_UPDATE = "PATCHD_EVENTO_UPDATE";
const PATCHD_PROPUESTA_UPDATE = "PATCHD_PROPUESTA_UPDATE";
const PATCHD_POLITICO_UPDATE = "PATCHD_POLITICO_UPDATE";

const PATCHD_EVENTO_DELETE = "PATCHD_EVENTO_DELETE";
const PATCHD_PROPUESTA_DELETE = "PATCHD_PROPUESTA_DELETE";
const PATCHD_POLITICO_DELETE = "PATCHD_POLITICO_DELETE";

const PATCH_EVENTO_ADD_MODERADOR = "PATCH_EVENTO_ADD_MODERADOR";
const PATCH_PROPUESTA_ADD_MODERADOR = "PATCH_PROPUESTA_ADD_MODERADOR";
const PATCH_POLITICO_ADD_MODERADOR = "PATCH_POLITICO_ADD_MODERADOR";

const PATCH_EVENTO_UPDATE_MODERADOR = "PATCH_EVENTO_UPDATE";
const PATCH_PROPUESTA_UPDATE_MODERADOR = "PATCH_PROPUESTA_UPDATE_MODERADOR";
const PATCH_POLITICO_UPDATE_MODERADOR = "PATCH_POLITICO_UPDATE_MODERADOR";

const PATCH_EVENTO_DELETE_MODERADOR = "PATCH_EVENTO_DELETE_MODERADOR";
const PATCH_PROPUESTA_DELETE_MODERADOR = "PATCH_PROPUESTA_DELETE_MODERADOR";
const PATCH_POLITICO_DELETE_MODERADOR = "PATCH_POLITICO_DELETE_MODERADOR";

//Se exportan las constantes
module.exports = {
    EVENTO_ADD,
    PROPUESTA_ADD, 
    POLITICO_ADD,

    EVENTO_UPDATE,
    PROPUESTA_UPDATE, 
    POLITICO_UPDATE,

    EVENTO_DELETE,
    PROPUESTA_DELETE, 
    POLITICO_DELETE,

    PATCH_EVENTO_ADD,
    PATCH_PROPUESTA_ADD, 
    PATCH_POLITICO_ADD,

    PATCH_EVENTO_UPDATE,
    PATCH_PROPUESTA_UPDATE, 
    PATCH_POLITICO_UPDATE,

    PATCH_EVENTO_DELETE,
    PATCH_PROPUESTA_DELETE, 
    PATCH_POLITICO_DELETE,

    PATCHD_EVENTO_ADD,
    PATCHD_PROPUESTA_ADD, 
    PATCHD_POLITICO_ADD,

    PATCHD_EVENTO_UPDATE,
    PATCHD_PROPUESTA_UPDATE, 
    PATCHD_POLITICO_UPDATE,

    PATCHD_EVENTO_DELETE,
    PATCHD_PROPUESTA_DELETE, 
    PATCHD_POLITICO_DELETE,
    
    PATCH_EVENTO_ADD_MODERADOR,
    PATCH_PROPUESTA_ADD_MODERADOR, 
    PATCH_POLITICO_ADD_MODERADOR,

    PATCH_EVENTO_UPDATE_MODERADOR,
    PATCH_PROPUESTA_UPDATE_MODERADOR, 
    PATCH_POLITICO_UPDATE_MODERADOR,

    PATCH_EVENTO_DELETE_MODERADOR,
    PATCH_PROPUESTA_DELETE_MODERADOR, 
    PATCH_POLITICO_DELETE_MODERADOR
};